os: linux
dist: bionic
sudo: required
language: generic
env:
  global:
    - CONDA_ROOT=$HOME/miniconda
addons:
  apt:
    update: true

before_install:
  # install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $CONDA_ROOT
  - echo ". $CONDA_ROOT/etc/profile.d/conda.sh" >> ~/.bashrc
  - source ~/.bashrc
  # update conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -q conda-build pip

install:
  # we need the cpape channel because nifty is not on conda-forge yet.
  # remove it once we have nifty on conda
  - conda build -c conda-forge -c defaults -c cpape --python=3.7 conda-recipe

before_script:
  - conda create -n test-env -c conda-forge -c defaults -c cpape --use-local python=3.7 elf
  - conda activate test-env
  # we still need to install zarr and pyn5, because they are not included by conda
  - conda install -c conda-forge -c defaults zarr
  - pip install pyn5

script:
  - cd test && python -m unittest discover -v .
